=== hectoruhalte/ITS/adaptacion/Schemas/vehiculos.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
   Titulo	: vehiculos.xsd
   Fecha	: 6/10/2017
   Autor	: Hector Uhalte Bilbao
-->
<schema
	attributeFormDefault="unqualified"
   	elementFormDefault="qualified"
   	finalDefault="#all"
   	targetNamespace="IntelligentTransportSystem"
   	version="1.0.0"
   	xmlns="http://www.w3.org/2001/XMLSchema"
   	xmlns:xs="http://www.w3.org/2001/XMLSchema"
   	xmlns:its="IntelligentTransportSystem">

   	<include schemaLocation="TiposBasicosAdaptacion.xsd"/>

   	<annotation>
    	<documentation>
        	Esquema para definir la adaptacion de los vehiculos
      	</documentation>
   	</annotation>

   	<!-- schema root element -->
   	<element name="vehiculoSet" type="its:VehiculoTipoSet"/>
   
   	<complexType name="VehiculoTipoSet">
    	<annotation>
        	<documentation>
				Tipo que va a contener la definicion de vehiculo.
         	</documentation>
      	</annotation>
      	<sequence>
         	<element name="datosVehiculo" type="its:DatosVehiculoTipo" minOccurs="0" maxOccurs="1000">
           		<annotation>
               		<documentation>
                  		Conjunto de datos para el tipo vehiculo
               		</documentation>
            	</annotation>
         	</element>
     	 </sequence>
   	</complexType>
   
   	<complexType name="DatosVehiculoTipo">
    	<annotation>
         	<documentation>
            	Conjunto de datos para el tipo vehiculo
         	</documentation>
      	</annotation>
      	<sequence>
        	<element name="marcaVehiculo" type="its:NombreMarcaModelo" minOccurs="1" maxOccurs="1">
            	<annotation>
               		<documentation>
                  		Marca del vehiculo
               		</documentation>
            	</annotation>
         	</element>
			<element name="modeloVehiculo" type="its:NombreMarcaModelo" minOccurs="1" maxOccurs="1">
            	<annotation>
               		<documentation>
                    	Modelo del vehiculo
                   	</documentation>
                </annotation>
            </element>
            <element name="caracteristicasVehiculo" type="its:CaracteristicasVehiculo" minOccurs="1" maxOccurs="1">
            	<annotation>
               		<documentation>
                    	Caracteristicas del vehiculo. Velocidad m√°xima, consumo, dimensiones.
                   	</documentation>
                </annotation>
            </element>
    	</sequence>
    </complexType>
            
	<complexType name="CaracteristicasVehiculo">    
		<annotation>
         	<documentation>
            	Caracteristicas del vehiculo.
         	</documentation>
      	</annotation>
      	<sequence>		
			<element name="velocidadMaxima" type="its:Velocidad" minOccurs="1" maxOccurs="1">
           		<annotation>
                	<documentation>
                    	Velocidad maxima que puede alcanzar el vehiculo
                  	</documentation>
                </annotation>
            </element>
			<element name="longitud" type="its:Longitud" minOccurs="1" maxOccurs="1">
            	<annotation>
                	<documentation>
                    	Longitud del vehiculo
                  	</documentation>
                </annotation>
          	</element>
			<element name="altura" minOccurs="1" maxOccurs="1">
            	<annotation>
               		<documentation>
                    	Altura del vehiculo
                    </documentation>
               	</annotation>
               	<simpleType>
               		<restriction base="double">
               			<minInclusive value="0.0"/>
               			<maxInclusive value="20.0"/>
               		</restriction>
               	</simpleType>
           	</element>
			<element name="consumoUrbano" type="its:Consumo" minOccurs="1" maxOccurs="1">
            	<annotation>
                	<documentation>
                   		Consumo de combustible en entorno urbano
                   	</documentation>
             	</annotation>
            </element>
			<element name="consumoCarretera" type="its:Consumo" minOccurs="1" maxOccurs="1">
            	<annotation>
               		<documentation>
                    	Consumo de combustible en entorno no urbano
                    </documentation>
                </annotation>
            </element>
      	</sequence>
 	</complexType>

</schema>

=== hectoruhalte/ITS/adaptacion/vehiculos.xml
<?xml version="1.0" encoding="UTF-8"?>
<its:vehiculoSet xmlns:its="IntelligentTransportSystem"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="IntelligentTransportSystem Schemas/vehiculos.xsd">
	<its:datosVehiculo>
		<its:marcaVehiculo>CITROEN   </its:marcaVehiculo>
		<its:modeloVehiculo>C3     </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>185</its:velocidadMaxima>
			<its:longitud>3.996</its:longitud>
			<its:altura>1.49</its:altura>
			<its:consumoUrbano>4.4</its:consumoUrbano>
			<its:consumoCarretera>3.2</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>CITROEN   </its:marcaVehiculo>
		<its:modeloVehiculo>C4     </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>200</its:velocidadMaxima>
			<its:longitud>4.329</its:longitud>
			<its:altura>1.49</its:altura>
			<its:consumoUrbano>5.93</its:consumoUrbano>
			<its:consumoCarretera>4.7</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>DACIA     </its:marcaVehiculo>
		<its:modeloVehiculo>SANDERO</its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>175</its:velocidadMaxima>
			<its:longitud>4.069</its:longitud>
			<its:altura>1.523</its:altura>
			<its:consumoUrbano>6.5</its:consumoUrbano>
			<its:consumoCarretera>4.5</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>NISSAN    </its:marcaVehiculo>
		<its:modeloVehiculo>QASHQAI</its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>200</its:velocidadMaxima>
			<its:longitud>4.394</its:longitud>
			<its:altura>1.59</its:altura>
			<its:consumoUrbano>5.5</its:consumoUrbano>
			<its:consumoCarretera>4.9</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>OPEL      </its:marcaVehiculo>
		<its:modeloVehiculo>CORSA  </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>177</its:velocidadMaxima>
			<its:longitud>4.021</its:longitud>
			<its:altura>1.485</its:altura>
			<its:consumoUrbano>6.8</its:consumoUrbano>
			<its:consumoCarretera>4.3</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>PEUGEOT   </its:marcaVehiculo>
		<its:modeloVehiculo>208    </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>190</its:velocidadMaxima>
			<its:longitud>3.962</its:longitud>
			<its:altura>1.46</its:altura>
			<its:consumoUrbano>8.1</its:consumoUrbano>
			<its:consumoCarretera>4.5</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>PEUGEOT   </its:marcaVehiculo>
		<its:modeloVehiculo>3008   </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>189</its:velocidadMaxima>
			<its:longitud>4.447</its:longitud>
			<its:altura>1.623</its:altura>
			<its:consumoUrbano>6.0</its:consumoUrbano>
			<its:consumoCarretera>5.1</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>RENAULT   </its:marcaVehiculo>
		<its:modeloVehiculo>CLIO   </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>167</its:velocidadMaxima>
			<its:longitud>4.062</its:longitud>
			<its:altura>1.448</its:altura>
			<its:consumoUrbano>7.2</its:consumoUrbano>
			<its:consumoCarretera>4.7</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>RENAULT   </its:marcaVehiculo>
		<its:modeloVehiculo>MEGANE </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>182</its:velocidadMaxima>
			<its:longitud>4.359</its:longitud>
			<its:altura>1.447</its:altura>
			<its:consumoUrbano>6.7</its:consumoUrbano>
			<its:consumoCarretera>4.6</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>SEAT      </its:marcaVehiculo>
		<its:modeloVehiculo>ARONA  </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>205</its:velocidadMaxima>
			<its:longitud>4.138</its:longitud>
			<its:altura>1.552</its:altura>
			<its:consumoUrbano>6.3</its:consumoUrbano>
			<its:consumoCarretera>4.4</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>SEAT      </its:marcaVehiculo>
		<its:modeloVehiculo>IBIZA  </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>182</its:velocidadMaxima>
			<its:longitud>4.059</its:longitud>
			<its:altura>1.444</its:altura>
			<its:consumoUrbano>6.1</its:consumoUrbano>
			<its:consumoCarretera>4.7</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>SEAT      </its:marcaVehiculo>
		<its:modeloVehiculo>LEON   </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>194</its:velocidadMaxima>
			<its:longitud>4.282</its:longitud>
			<its:altura>1.459</its:altura>
			<its:consumoUrbano>8.28</its:consumoUrbano>
			<its:consumoCarretera>6.1</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>VOLKSWAGEN</its:marcaVehiculo>
		<its:modeloVehiculo>GOLF   </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>220</its:velocidadMaxima>
			<its:longitud>4.65</its:longitud>
			<its:altura>1.65</its:altura>
			<its:consumoUrbano>6.5</its:consumoUrbano>
			<its:consumoCarretera>4.0</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
	<its:datosVehiculo>
		<its:marcaVehiculo>VOLKSWAGEN</its:marcaVehiculo>
		<its:modeloVehiculo>POLO   </its:modeloVehiculo>
		<its:caracteristicasVehiculo>
			<its:velocidadMaxima>187</its:velocidadMaxima>
			<its:longitud>4.053</its:longitud>
			<its:altura>1.461</its:altura>
			<its:consumoUrbano>6.2</its:consumoUrbano>
			<its:consumoCarretera>4.8</its:consumoCarretera>
		</its:caracteristicasVehiculo>
	</its:datosVehiculo>
</its:vehiculoSet>
